extends:
  - '@commitlint/config-conventional'
rules:
  body-max-line-length: [0, 'always', 100]
  footer-max-line-length: [0, 'always', 100]
  header-max-length: [0, 'always', 150]
  scope-case: [2, 'always', 'lower-case']
  subject-case: [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']]