version: "2"

run:
  timeout: 5m
  tests: true

linters:
  disable-all: true
  enable:
    - misspell
    - revive
    - bodyclose
    - errname
  disable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  # Exclude all issues from default linters that are not in the original configuration
  exclude-use-default: false
