version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - misspell
    - revive
    - bodyclose
    - errname
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused

issues:
  # Don't exclude issues from the enabled linters
  exclude-use-default: false
