version: '2'
services:
  tarmac-performance:
    build: .
    ports:
      - 443:8443
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_WASM_FUNCTION=/testdata/default/tarmac.wasm"
    volumes:
      - "./testdata:/testdata"
  tarmac:
    build: .
    ports:
      - 443:8443
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_USE_CONSUL=true"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
      - "APP_WASM_FUNCTION_CONFIG=/testdata/tarmac.json"
      - "ENABLE_SQL=true"
      - "ENABLE_KVSTORE=true"
      - "SQL_TYPE=mysql"
      - "SQL_DSN=root:example@tcp(mysql:3306)/example"
      - "KVSTORE_TYPE=redis"
      - "REDIS_SERVER=redis:6379"
    volumes:
      - "./testdata:/testdata"
    depends_on:
      - mysql
      - redis
      - consul
      - consulator
  tests-base:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -skip "TestFullService/.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - redis
      - consul
      - consulator
      - mysql
  tests-inmemory:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/In-Memory.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - consul
      - consulator
  tests-boltdb:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/BoltDB.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - consul
      - consulator
  tests-redis:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/Redis.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - redis
      - consul
      - consulator
  tests-cassandra:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/Cassandra.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - cassandra-primary
      - cassandra
      - consul
      - consulator
  tests-mysql:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/MySQL.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - mysql
      - consul
      - consulator
  tests-postgres:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/Postgres.*" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - postgres
      - consul
      - consulator
  benchmarks:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -run=XXX -bench=. ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - redis
      - cassandra-primary
      - cassandra
      - consul
      - consulator
      - mysql
      - postgres
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  cassandra-primary:
    image: madflojo/cassandra:latest
    environment:
      - CASSANDRA_KEYSPACE=tarmac
      - SLEEP_TIMER=1
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  cassandra:
    image: madflojo/cassandra:latest
    environment:
      - CASSANDRA_SEEDS=cassandra-primary
      - CASSANDRA_KEYSPACE=tarmac
      - SLEEP_TIMER=15
    depends_on:
      - cassandra-primary
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  mysql:
    image: bitnami/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
  postgres:
    image: bitnami/postgresql:latest
    restart: always
    environment:
      - POSTGRESQL_USERNAME=example
      - POSTGRESQL_PASSWORD=example
      - POSTGRESQL_DATABASE=example
    ports:
      - 5432:5432
  consul:
    image: bitnami/consul:latest
    ports:
      - 8500:8500
  consulator:
    image: lewispeckover/consulator
    command: "import /app/testdata/tarmac-consul.yml"
    depends_on:
      - consul
    volumes:
      - "./:/app"
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"

  nats:
    image: nats:latest
    ports:
      - "4222:4222"

  tests-nats-runner:
    image: golang:latest
    working_dir: /go/src/github.com/tarmac-project/tarmac
    entrypoint: go test -v -race -covermode=atomic -coverprofile=/tmp/coverage/coverage.out -run "TestFullService/NATS KV Full Service" ./...
    volumes:
      - "./:/go/src/github.com/tarmac-project/tarmac"
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false" # Common in other test services
      - "APP_CONSUL_ADDR=consul:8500" # Common in other test services
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config" # Common in other test services
      - "CONSUL_HTTP_ADDR=consul:8500" # Common in other test services
      - "CONSUL_HTTP_SSL=false" # Common in other test services
      - "CI=true" # Ensure tests that might check for CI env run
    depends_on:
      - nats
      - consul      # Added as TestFullService tarmac.json might use it
      - consulator  # Added as TestFullService tarmac.json might use it

volumes:
  coverage:
