version: '2'
services:
  tarmac-performance:
    build: .
    ports:
      - 443:8443
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_WASM_FUNCTION=testdata/default/tarmac.wasm"
  tarmac:
    build: .
    ports:
      - 443:8443
      - 80:8080
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_LISTEN_ADDR=0.0.0.0:8080"
      - "APP_USE_CONSUL=true"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
      - "APP_WASM_FUNCTION_CONFIG=./testdata/tarmac.json"
      - "ENABLE_SQL=true"
      - "ENABLE_KVSTORE=true"
      - "SQL_TYPE=mysql"
      - "SQL_DSN=root:example@tcp(mysql:3306)/example"
      - "KVSTORE_TYPE=redis"
      - "REDIS_SERVER=redis:6379"
    volumes:
      - "./testdata:/testdata"
    depends_on:
      - redis
      - consul
      - consulator
  tests:
    build: .
    working_dir: /go/src/github.com/madflojo/tarmac
    entrypoint: go test -v -covermode=count -coverprofile=/tmp/coverage/coverage.out ./...
    volumes:
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - redis
      - cassandra-primary
      - cassandra
      - consul
      - consulator
      - mysql
  benchmarks:
    build: .
    working_dir: /go/src/github.com/madflojo/tarmac
    entrypoint: go test -v -run=XXX -bench=. ./...
    volumes:
      - "./coverage:/tmp/coverage"
      - "./example:/example"
      - "./testdata:/testdata"
    environment:
      - "APP_ENABLE_TLS=false"
      - "APP_CONSUL_ADDR=consul:8500"
      - "APP_CONSUL_KEYS_PREFIX=tarmac/config"
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"
    depends_on:
      - redis
      - cassandra-primary
      - cassandra
      - consul
      - consulator
      - mysql
  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
  cassandra-primary:
    image: madflojo/cassandra:latest
    command: /bin/bash -c "sleep 1 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_KEYSPACE=tarmac
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  cassandra:
    image: madflojo/cassandra:latest
    command: /bin/bash -c "sleep 15 && /docker-entrypoint.sh cassandra -f"
    environment:
      - CASSANDRA_SEEDS=cassandra-primary
      - CASSANDRA_KEYSPACE=tarmac
    depends_on:
      - cassandra-primary
    expose:
      - 7000
      - 7001
      - 7199
      - 9042
      - 9160
  mysql:
    image: bitnami/mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: example
    ports:
      - 3306:3306
  consul:
    image: consul
    ports:
      - 8500:8500
  consulator:
    image: lewispeckover/consulator
    command: "import /app/tarmac-consul.yml"
    depends_on:
      - consul
    volumes:
      - "./:/app"
    environment:
      - "CONSUL_HTTP_ADDR=consul:8500"
      - "CONSUL_HTTP_SSL=false"

volumes:
  coverage:
